apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-app-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: backstage
data:
  app-config.kind.yaml: |
{{ .Values.appConfig | indent 4 }}
